import { useEffect, useState, useRef, useCallback } from "react";
import { toast } from "sonner";
import { Header } from "../components/Header";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Badge } from "../components/ui/badge";
import {
  Lightbulb,
  AlertCircle,
  CheckCircle2,
  TrendingUp,
  Sparkles,
  ArrowRight,
  X,
  Check,
  Loader2,
} from "lucide-react";
import { getInsights, generateInsights, markInsightCompleted, getResumes, type ResumeInsight } from "../../lib/api";
import { motion, AnimatePresence } from "motion/react";

export function Insights() {
  const [insights, setInsights] = useState<ResumeInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [updatingId, setUpdatingId] = useState<number | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const loadInsights = () => {
    setLoading(true);
    getInsights()
      .then(setInsights)
      .catch(() => toast.error("Failed to load insights"))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadInsights();
  }, []);

  useEffect(() => {
    try {
      const pending = localStorage.getItem("hiresense:insights-pending");
      if (pending) {
        localStorage.removeItem("hiresense:insights-pending");
        toast.info("Regenerating insights for the new resume...");
      }
    } catch {}
  }, []);

  const handleGenerate = useCallback(() => {
    setGenerating(true);
    generateInsights()
      .then((data) => {
        setInsights(data);
        if (data.length > 0) toast.success(`Generated ${data.length} insights`);
        else toast.info("No insights generated. Ensure your resume is uploaded and OPENAI_API_KEY is set.");
      })
      .catch((err: Error & { body?: { detail?: string } }) => {
        const msg = err?.body?.detail ?? err?.message ?? "Failed to generate insights";
        toast.error(msg);
      })
      .finally(() => setGenerating(false));
  }, []);

  // Auto-generate insights on first visit if user has a resume but no insights
  useEffect(() => {
    const autoGenerate = async () => {
      if (loading || generating || hasAutoGeneratedRef.current) return;
      if (insights.length > 0) return; // Already has insights
      
      try {
        const resumes = await getResumes();
        const hasResume = Array.isArray(resumes) && resumes.length > 0;
        
        if (hasResume && insights.length === 0 && !hasAutoGeneratedRef.current) {
          hasAutoGeneratedRef.current = true;
          toast.info("Generating your first insights...");
          handleGenerate();
        }
      } catch {
        // Silently fail - user can manually generate if needed
      }
    };

    autoGenerate();
  }, [loading, insights.length, generating, handleGenerate]);

  const handleMarkCompleted = async (id: number, completed: boolean) => {
    setUpdatingId(id);
    const prev = insights.find((i) => i.id === id);
    const prevCompleted = prev?.completed_at ?? null;
    setInsights((prevList) =>
      prevList.map((i) =>
        i.id === id ? { ...i, completed_at: completed ? new Date().toISOString() : null } : i
      )
    );
    try {
      const updated = await markInsightCompleted(id, completed);
      setInsights((prevList) => prevList.map((i) => (i.id === id ? updated : i)));
    } catch {
      setInsights((prevList) =>
        prevList.map((i) => (i.id === id ? { ...i, completed_at: prevCompleted } : i))
      );
      toast.error("Failed to update");
    } finally {
      setUpdatingId(null);
    }
  };

  const allInsights = [...insights].sort((a, b) => {
    const o: Record<string, number> = { critical: 0, important: 1, suggestion: 2 };
    return (o[a.category] ?? 2) - (o[b.category] ?? 2);
  });

  const incomplete = insights.filter((i) => !i.completed_at);
  const criticalCount = incomplete.filter((i) => i.category === "critical").length;
  const importantCount = incomplete.filter((i) => i.category === "important").length;
  const suggestionCount = incomplete.filter((i) => i.category === "suggestion").length;

  const getPriorityBadge = (category: string) => {
    if (category === "critical") return <Badge className="bg-red-600 text-white border-0">Critical</Badge>;
    if (category === "important") return <Badge className="bg-orange-500 text-white border-0">Important</Badge>;
    return <Badge variant="outline" className="border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300">Suggestion</Badge>;
  };

  const getCategoryIcon = (category: string) => {
    if (category === "critical") return <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-500" />;
    if (category === "important") return <TrendingUp className="w-5 h-5 text-orange-500 dark:text-orange-400" />;
    return <Lightbulb className="w-5 h-5 text-gray-600 dark:text-gray-400" />;
  };

  return (
    <div className="flex flex-col h-full overflow-auto">
      <Header
        title="Resume Insights"
        subtitle="AI-powered suggestions to improve your resume and increase match rates"
      />

      <div className="flex-1 p-4 sm:p-6 lg:p-8 space-y-4 sm:space-y-6 pb-20 lg:pb-8">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Card className="bg-gradient-to-r from-emerald-600 to-teal-600 border-0 text-white">
            <CardContent className="p-4 sm:p-6">
              <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 sm:gap-6">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-2 sm:mb-3">
                    <Sparkles className="w-5 h-5 sm:w-6 sm:h-6" />
                    <h3 className="text-lg sm:text-xl font-semibold">Potential Impact</h3>
                  </div>
                  <p className="text-emerald-100 text-sm mb-4">
                    Apply each suggestion manually (e.g. update your resume), then mark it as completed in the list below.
                  </p>
                  <div className="grid grid-cols-2 gap-4 sm:gap-6">
                    <div>
                      <div className="text-2xl sm:text-3xl font-bold">{incomplete.length}</div>
                      <div className="text-xs sm:text-sm text-emerald-100">Remaining</div>
                    </div>
                    <div>
                      <div className="text-2xl sm:text-3xl font-bold">{criticalCount + importantCount}</div>
                      <div className="text-xs sm:text-sm text-emerald-100">High Priority</div>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <div className="grid grid-cols-3 gap-3 sm:gap-4">
          <motion.div
            className="flex flex-col sm:flex-row items-center sm:items-center gap-2 sm:gap-3 p-3 sm:p-4 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <div className="text-3xl sm:text-4xl">🚨</div>
            <div className="text-center sm:text-left">
              <div className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-gray-100">{criticalCount}</div>
              <div className="text-xs sm:text-sm text-gray-600 dark:text-gray-400">Critical</div>
            </div>
          </motion.div>
          <motion.div
            className="flex flex-col sm:flex-row items-center sm:items-center gap-2 sm:gap-3 p-3 sm:p-4 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <div className="text-3xl sm:text-4xl">⚠️</div>
            <div className="text-center sm:text-left">
              <div className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-gray-100">{importantCount}</div>
              <div className="text-xs sm:text-sm text-gray-600 dark:text-gray-400">Important</div>
            </div>
          </motion.div>
          <motion.div
            className="flex flex-col sm:flex-row items-center sm:items-center gap-2 sm:gap-3 p-3 sm:p-4 bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
          >
            <div className="text-3xl sm:text-4xl">💡</div>
            <div className="text-center sm:text-left">
              <div className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-gray-100">{suggestionCount}</div>
              <div className="text-xs sm:text-sm text-gray-600 dark:text-gray-400">Suggestions</div>
            </div>
          </motion.div>
        </div>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle>All Recommendations</CardTitle>
            <Button
              variant="outline"
              size="sm"
              onClick={handleGenerate}
              disabled={generating}
              className="shrink-0"
            >
              {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              <span className="ml-2 hidden sm:inline">Regenerate</span>
            </Button>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="py-12 flex items-center justify-center">
                <Loader2 className="w-8 h-8 animate-spin text-emerald-600" />
              </div>
            ) : (
              <AnimatePresence mode="popLayout">
                {allInsights.length === 0 ? (
                  <motion.div
                    className="text-center py-12"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                  >
                    <Sparkles className="w-12 h-12 text-emerald-600 dark:text-emerald-400 mx-auto mb-3" />
                    <p className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">
                      {insights.length === 0 ? "No insights yet" : "All Caught Up!"}
                    </p>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
                      {insights.length === 0
                        ? "Upload your resume first, then generate AI-powered suggestions."
                        : "You have no visible insights. Generate new ones from your latest resume."}
                    </p>
                    <Button
                      onClick={handleGenerate}
                      disabled={generating}
                      className="bg-gradient-to-r from-emerald-600 to-teal-600"
                    >
                      {generating ? (
                        <>
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                          Generating…
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-4 h-4 mr-2" />
                          Generate Insights
                        </>
                      )}
                    </Button>
                  </motion.div>
                ) : (
                  <div className="space-y-3">
                    {allInsights.map((insight, index) => (
                      <motion.div
                        key={insight.id}
                        layout
                        className={`flex flex-col sm:flex-row sm:items-start gap-3 sm:gap-4 p-4 border ${
                          insight.completed_at
                            ? "bg-emerald-50/50 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-800"
                            : "bg-gray-50 dark:bg-gray-800 border-gray-200 dark:border-gray-700"
                        }`}
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, x: -100 }}
                        transition={{ duration: 0.3, delay: index * 0.05 }}
                      >
                        <div className="flex items-start gap-3 sm:gap-4 flex-1">
                          <div className="w-10 h-10 sm:w-12 sm:h-12 flex items-center justify-center flex-shrink-0">
                            {getCategoryIcon(insight.category)}
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 mb-2">
                              <h4
                                className={`font-semibold ${
                                  insight.completed_at
                                    ? "text-gray-500 dark:text-gray-400 line-through"
                                    : "text-gray-900 dark:text-gray-100"
                                }`}
                              >
                                {insight.title}
                              </h4>
                              <div className="flex flex-wrap items-center gap-2">
                                {getPriorityBadge(insight.category)}
                                {insight.completed_at && (
                                  <Badge className="bg-emerald-600 text-white border-0">Completed</Badge>
                                )}
                              </div>
                            </div>
                            <p className="text-sm text-gray-600 dark:text-gray-400">{insight.description}</p>
                            <div className="mt-3 flex flex-col sm:flex-row sm:items-center gap-2">
                              <Badge variant="outline" className="text-xs w-fit">
                                {insight.impact}
                              </Badge>
                              <div className="flex gap-2 sm:ml-auto">
                                {insight.completed_at ? (
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={() => handleMarkCompleted(insight.id, false)}
                                    disabled={updatingId === insight.id}
                                  >
                                    {updatingId === insight.id ? (
                                      <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                                    ) : (
                                      <>
                                        <X className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                                        Clear
                                      </>
                                    )}
                                  </Button>
                                ) : (
                                  <Button
                                    size="sm"
                                    className="bg-gradient-to-r from-emerald-600 to-teal-600"
                                    onClick={() => handleMarkCompleted(insight.id, true)}
                                    disabled={updatingId === insight.id}
                                  >
                                    {updatingId === insight.id ? (
                                      <Loader2 className="w-3 h-3 sm:w-4 sm:h-4 animate-spin" />
                                    ) : (
                                      <>
                                        <Check className="w-3 h-3 sm:w-4 sm:h-4 mr-1" />
                                        Mark as completed
                                      </>
                                    )}
                                  </Button>
                                )}
                              </div>
                            </div>
                          </div>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                )}
              </AnimatePresence>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
