# Generated by Django 5.2.11 on 2026-02-18 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in sites (e.g. LinkedIn, Indeed) cannot be deleted by user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for global built-in sites; set for user-added sites.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_job_site',
                'ordering': ['-is_builtin', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('match_score', models.PositiveIntegerField(help_text='0-100 resume vs job description match.')),
                ('interview_probability', models.PositiveIntegerField(help_text='0-100 estimated interview probability.')),
                ('skills', models.JSONField(default=list, help_text='List of skills that matched (strings).')),
                ('missing_skills', models.JSONField(default=list, help_text='List of skills in job description not found on resume.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
                ('job_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_matches', to='core.jobsite')),
            ],
            options={
                'verbose_name_plural': 'Job matches',
                'db_table': 'core_job_match',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='resumes/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('parsed_content', models.JSONField(blank=True, default=dict, help_text='Structured data: skills, experience, education, summary, etc.')),
                ('raw_text', models.TextField(blank=True, help_text='Plain text extraction for search/display.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_resume',
                'ordering': ['-uploaded_at'],
                'get_latest_by': 'uploaded_at',
            },
        ),
        migrations.CreateModel(
            name='ResumeInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('suggestion', 'Suggestion')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(blank=True, help_text='Insight for this resume version; null if general.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_resume_insight',
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_user_profile',
            },
        ),
        migrations.AddConstraint(
            model_name='jobsite',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'url'), name='core_job_site_user_url_unique'),
        ),
    ]
