# Generated by Django 5.2.11 on 2026-02-18 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='scrape_config',
            field=models.JSONField(blank=True, default=dict, help_text='Extra config: keywords, location, CSS selectors, etc.'),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS/Atom Feed'), ('generic', 'Generic Scraper'), ('indeed', 'Indeed (API/RSS)'), ('linkedin', 'LinkedIn (API key required)'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter')], default='rss', help_text='How to fetch jobs: RSS feed, generic scraper, or specific API.', max_length=20),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('external_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Job description for matching.')),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_job_posting',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source'], name='core_job_po_source_d2dd55_idx'), models.Index(fields=['fetched_at'], name='core_job_po_fetched_0d6564_idx')],
                'unique_together': {('source', 'external_url')},
            },
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.jobposting'),
        ),
    ]
