# Generated by Django (HireSense)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobposting_and_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobmatch",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
