# Generated by Django 5.2.11 on 2026-02-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobmatch_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile photo.', null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='jobmatch',
            name='applied_at',
            field=models.DateTimeField(blank=True, help_text='When the user marked this job as applied (application completed).', null=True),
        ),
    ]
