# Generated by Django 5.2.11 on 2026-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeinsight',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the user marked this suggestion as completed (applied manually).', null=True),
        ),
    ]
