# Generated by Django 5.2+ - add primary_resume to UserProfile

from django.db import migrations, models
import django.db.models.deletion


def get_resume_model(apps):
    return apps.get_model("core", "Resume")


def get_profile_model(apps):
    return apps.get_model("core", "UserProfile")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_resume_insight_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="primary_resume",
            field=models.ForeignKey(
                blank=True,
                help_text="Resume used for job matches and insights when set; otherwise latest by upload.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_profiles",
                to="core.resume",
            ),
        ),
    ]
