# Generated by Django 5.2.11 on 2026-02-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_primary_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS/Atom Feed'), ('generic', 'Generic Scraper'), ('indeed', 'Indeed (API/RSS)'), ('linkedin', 'LinkedIn (API key required)'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter'), ('remotive', 'Remotive (API)')], default='rss', help_text='How to fetch jobs: RSS feed, generic scraper, or specific API.', max_length=20),
        ),
    ]
