# Generated by Django 5.2.11 on 2026-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_remotive_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Get daily summaries of new matches via email.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='high_match_alerts',
            field=models.BooleanField(default=True, help_text='Instant alerts for 85%+ matches.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_reports',
            field=models.BooleanField(default=False, help_text='Summary of activity and insights sent weekly.'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='source_type',
            field=models.CharField(choices=[('rss', 'RSS/Atom Feed'), ('generic', 'Generic Scraper'), ('indeed', 'Indeed (API/RSS)'), ('linkedin', 'LinkedIn (API key required)'), ('glassdoor', 'Glassdoor'), ('ziprecruiter', 'ZipRecruiter')], default='rss', help_text='How to fetch jobs: RSS feed, generic scraper, or specific API.', max_length=20),
        ),
    ]
