# Generated by Django 5.2.11 on 2026-02-20 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_email_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('important', 'Important Update'), ('info', 'Information'), ('alert', 'Alert'), ('warning', 'Warning')], default='info', max_length=20)),
                ('is_sent', models.BooleanField(default=False, help_text='Whether the notification has been sent to users.')),
                ('send_immediately', models.BooleanField(default=True, help_text='If False, notification is drafted and can be scheduled for later.')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When the notification should be sent.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was actually sent.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Superuser who created this notification.', on_delete=django.db.models.deletion.PROTECT, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_system_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_syste_created_idx'), models.Index(fields=['is_sent', 'send_immediately'], name='core_syste_is_sent_idx')],
            },
        ),
    ]
